# fly.toml app configuration file generated for readme-ascii on 2024-06-29T15:18:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'readme-ascii'
primary_region = 'iad'
console_command = 'npm start'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
